# -*- coding: utf-8 -*-
"""Final Data Visualization(Project).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zbleU4kvj-GnNTr-Fx_5OcwSjQDZ_pAg
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")
plt.rcParams["figure.figsize"] = (10, 6)

from google.colab import drive
drive.mount('/content/drive')

import os
os.listdir("/content/drive/MyDrive/Data Visualization Project")

#load raw data
df = pd.read_csv("/content/drive/MyDrive/Data Visualization Project/national_M2024_dl.csv")
df.head()

df.dtypes

#this removes hidden spaces
df.columns = df.columns.str.strip()

#filter us only
df = df[df["AREA_TITLE"] == "U.S."]

#Select Needed Columns
df = df[["OCC_TITLE", "O_GROUP", "TOT_EMP", "H_MEAN", "A_MEAN"]]

#rename columns
df = df.rename(columns={
    "OCC_TITLE": "occupation",
    "O_GROUP": "soc_group",
    "TOT_EMP": "employment",
    "H_MEAN": "hourly_mean",
    "A_MEAN": "annual_mean"
})

#Remove Commas & Convert to Numeric
for col in ["employment", "hourly_mean", "annual_mean"]:
    # Remove commas
    df[col] = df[col].astype(str).str.replace(",", "", regex=False)
    # Convert to numeric
    df[col] = pd.to_numeric(df[col], errors="coerce")

#Drop Missing Values
df = df.dropna(subset=["employment", "annual_mean","hourly_mean"])

#FIX: remove the “All Occupations” row which distorts graphs
df = df[df["occupation"] != "All Occupations"]
df.head()

print(df.describe())

#saving clean data
df.to_csv("oews_clean_midterm.csv", index=False)

# from google.colab import files

# files.download("oews_clean_midterm.csv")

df = pd.read_csv("oews_clean_midterm.csv")
print(df.dtypes)
print(df.isna().sum())
print(df.shape)

"""Now data is clean"""

import matplotlib.pyplot as plt
import seaborn as sns

df.dtypes

df[["employment","hourly_mean","annual_mean"]] = df[["employment","hourly_mean","annual_mean"]].apply(pd.to_numeric)

"""Bar Plot — Top 15 Occupations by Employment"""

top15 = df.sort_values("employment", ascending=False).head(15)

plt.figure(figsize=(12,6))
sns.barplot(x="employment", y="occupation", data=top15, palette="viridis")

plt.xscale("log") # We added log scale to fix the problem where one large value was hiding all others.

plt.title("Top 15 Occupations by Employment in the U.S.")
plt.xlabel("Number of Employees")
plt.ylabel("Occupation")
for i, val in enumerate(top15["employment"]):
    plt.text(val, i, f"{int(val):,}", va='center', ha='left', fontsize=9)
plt.tight_layout()
plt.show()

"""Box Plot — Wage Distribution by Major Occupational Group"""

plt.figure(figsize=(12,6))
sns.boxplot(x="soc_group", y="annual_mean", data=df, palette="pastel")
plt.yscale("log")
plt.title("Annual Wage Distribution by Occupational Group")
plt.xlabel("Major Occupational Group")
plt.ylabel("Annual Mean Wage (USD, log scale)")
plt.tight_layout()
plt.show()

"""Scatter Plot — Employment vs. Average Wage"""

plt.figure(figsize=(12,6))
sns.scatterplot(x="employment", y="annual_mean", hue="soc_group", data=df, alpha=0.7)
plt.xscale("log")
plt.yscale("log")
plt.title("Employment vs Annual Mean Wage")
plt.xlabel("Employment (log scale)")
plt.ylabel("Annual Mean Wage (log scale)")
plt.tight_layout()
plt.show()

"""Histogram / Density — National Wage Distribution"""

plt.figure(figsize=(12,6))
sns.histplot(df["annual_mean"], bins=30, kde=True, color="skyblue")
plt.axvline(df["annual_mean"].mean(), color="red", linestyle="--", label="Mean")
plt.axvline(df["annual_mean"].median(), color="green", linestyle="--", label="Median")
plt.title("Distribution of Annual Mean Wages in the U.S.")
plt.xlabel("Annual Mean Wage (USD)")
plt.ylabel("Number of Occupations")
plt.legend()
plt.tight_layout()
plt.show()

"""**Final figure Plot **

Pie Chart — Employment Share by SOC Group
Story
"""

soc_employment = df.groupby("soc_group")["employment"].sum().sort_values(ascending=False)

plt.figure(figsize=(10,8))
plt.pie(soc_employment, labels=soc_employment.index, autopct="%1.1f%%", startangle=140, colors=sns.color_palette("tab20"))
plt.title("Employment Share by Major Occupational Group")
plt.tight_layout()
plt.show()

"""Violin Plot — Hourly Wage Distribution by SOC Group


"""

plt.figure(figsize=(12,6))
sns.violinplot(x="soc_group", y="hourly_mean", data=df, palette="pastel")
plt.title("Hourly Wage Distribution by Occupational Group")
plt.xlabel("Major Occupational Group")
plt.ylabel("Hourly Wage (USD)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""Correlation Heatmap



"""

corr = df[["employment","hourly_mean","annual_mean"]].corr()

plt.figure(figsize=(8,6))
sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation between Employment, Hourly Wage, and Annual Wage")
plt.tight_layout()
plt.show()

"""Bubble Plot — Employment vs Annual Wage (size = employment)"""

plt.figure(figsize=(12,6))
sns.scatterplot(x="employment", y="annual_mean", size="employment", hue="soc_group",
                data=df, alpha=0.6, sizes=(50,1000))
plt.xscale("log")
plt.yscale("log")
plt.title("Employment vs Annual Wage (Bubble Size = Employment)")
plt.xlabel("Employment (log scale)")
plt.ylabel("Annual Mean Wage (log scale)")
plt.tight_layout()
plt.show()